### save new city
POST http://localhost:8080/city/save
Content-Type: application/json

{
  "name": "Москва",
  "description": "Не забудьте посетить Красную площадь. Ну а в ЦУМ можно не заходить)))"
}

### get city
GET http://localhost:8080/city/desc/Москва

### update city
PUT http://localhost:8080/city/update/1
Content-Type: application/json

{
  "name": "Москва",
  "description": "Не забудьте посетить Красную площадь."
}

### delete city
DELETE http://localhost:8080/city/delete/1
